name: Build
on:
  - workflow_dispatch

jobs:
  compile-for-windows:
    name: Compile for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Compile Native Components
        shell: C:\msys64\usr\bin\bash.exe -e '{0}'
        run: |
          cd NativeComponents/
          make
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-windows
          path: |
            NativeComponents/ImGuizmo-Bridge.dll
            NativeComponents/ImGuizmo-Bridge.LICENSE.txt

  compile-for-linux:
    name: Compile for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Compile Native Components
        run: |
          cd NativeComponents/
          make
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: native-linux
          path: |
            NativeComponents/libImGuizmo-Bridge.so
            NativeComponents/ImGuizmo-Bridge.LICENSE.txt

  compile-net-wrapper:
    name: Compile .NET wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false # Don't need submodules here
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build .NET Library
        run: |
          cd ImGuizmo.NET
          dotnet build -c Release --nologo -o ../bin/Release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotnet
          path: |
            bin/Release/
