name: Create Release

# Only allow one of these at a time (in case of tag deletion)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags: [ 'v*' ]

jobs:
  build-release:
    name: Build Release
    uses: ./.github/workflows/build.yml
  upload-release:
    name: Upload Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build-release
    steps:
      - name: Download Package Artifact
        uses: actions/download-artifact@v3
        with:
          name: imguizmo
          path: package/
      - name: Create Release Zip
        run: |
          cd package/
          7z a ../ImGuizmo.NET.zip .
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          fail_on_unmatched_files: true
          files: ImGuizmo.NET.zip
